# Generated by Django 4.2.16 on 2024-10-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to='product_video/'),
        ),
    ]
