# Generated by Django 4.2.16 on 2024-10-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_product_product_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_video',
        ),
    ]
