# Generated by Django 4.2.16 on 2024-10-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
